[build]
  command = "npx prisma generate && npm run build"
  publish = ".next"

[build.environment]
  NODE_VERSION = "20"
  NEXT_TELEMETRY_DISABLED = "1"
  DATABASE_URL = "${NETLIFY_DATABASE_URL}"
  DIRECT_DATABASE_URL = "${NETLIFY_DATABASE_URL_UNPOOLED}"

[[plugins]]
  package = "@netlify/plugin-nextjs"
